version: '3.9'

services:
  db:
    container_name: iftm_db
    image: mysql:latest
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  api:
    container_name: recon_api
    build: .
    ports:
      - "8004:8000"
